baseURL = "https://cmdlimes.com/"
languageCode = "en-us"
title = "CMD Limes | Python Consultants"
theme = "navigator-hugo"
summaryLength = 10

# Build robots.txt file
enableRobotsTXT = true
# google analytics tracking id
googleAnalytics = "" # your analitics ID

enableGitInfo = false
pygmentsCodeFences = true

# Multilangues setup
# Renders the default content language in subdir, e.g. /en/. The root directory / will redirect to /en/
defaultContentLanguageInSubdir = false
DefaultContentLanguage = "en"

# Site Params
[params]
logo = "images/logo7.png"


# meta data
author = "CMD Limes"
description = "CMD Limes, LTD is a software agency and co-operative that prides itself as stewards of the Python community. Join us for our impressive experience and friendly culture. Complex problems become celebrated successes with our emphasis on strong client buy-in and leading-edge solutions. We have decades of experience in building performant, clean and robust code. We provide consultative advice and problem-solving software to achieve organizational goals while maintaining clarity on timelines, cost and quality."

# Gestion des langues : FR / EN / NL / DE
[Languages]


############# 2 - Site en ENGLISH
[Languages.en]
weight = 2
languageCode = "en-us"
title = "CMD Limes Python Consultants"
dateFormat = "January 2, 2006"
home = "Home"
logo = "images/logo7.png"
menufixed = false

#footerDescription = "Integer posuere erat a ante venenati dapibus posuere velit aliquet. Fusce dapibus, tellus cursus commodo, tortor mauris sed posuere."
#footerServiceTitle = "Service"
#footerQuicklinkTitle = "Quicklinks"
#footerAboutTitle = "About"
#footerSubscribeTitle = "Subscribe"


# cookies
[params.cookies]
enable = true
expire_days = 2

# Hero Area Section
[Languages.en.params.hero]
enable = true
heading = "CMD Limes Python Consultants"
description = "We are a software agency and co-operative that prides itself as stewards of the Python community. Join us for our impressive experience and friendly culture."
button = true
btnText = "Learn more"
btnURL = "#about"
#videoThumb = "images/slider/video-player-thumb.jpg"
#videoURL = "https://www.youtube.com/embed/g3-VxLQO7do"

# About 2 Section
[Languages.en.params.aboutSm]
enable = true
title = "Complex problems become celebrated successes with our emphasis on strong client buy-in and leading-edge solutions. "
description = "We have decades of experience in building performant, clean and robust code. We provide consultative advice and problem-solving software to achieve organizational goals while maintaining clarity on timelines, cost and quality."

# Blog Section On Homepage
[Languages.en.params.blog]
enable = false
topTitle = "OUR UNTOLD STORY"
title = "Blog."
subtitle = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"

# Contact Section
[Languages.en.params.contact]
enable = true
topTitle = "DROP US A NOTE"
title = "Get in touch"
subtitle = "Write to us at contact@cmdlimes.com"
#address = "14/05, Stockhome <br> Victori Palace , United States"
#phone = "(03) 9283 2617"
#fax = "+61 3827 3590"
#facebook = "https://www.facebook.com/"
#twitter = "https://twitter.com/"
#linkedin = "https://www.linkedin.com/"
#dribbble = "https://dribbble.com/"
#instagram = "https://www.instagram.com/"
#mapLatitude = "51.507351"
#mapLongitude = "-0.127758"
#mapMarker = "images/marker.png"

# Call to Action Section on About Page
[Languages.en.params.cta]
enable = true
bg = "images/call-to-action/call-to-action-bg-2.jpg"
title = "Let's Create Something Together"
subtitle = "Proin gravida nibh vel velit auctor aliquet. Aenean sollicudin bibendum auctor, <br> nisi elit consequat ipsum, nesagittis sem nid elit. Duis sed odio sitain elit."
btnText = "Contact Us"

# We Used Themefisher Icon font for Icon, for more details check this github repository - https://github.com/themefisher/themefisher-font

# Site Menus
[menu]
# Navbar Menus
[[menu.nav]]
name = "about"
url = "#about"
weight = 2
[[menu.nav]]
name = "team"
url = "#team"
weight = 3
#[[menu.nav]]
#name = "portfolio"
#url = "portfolio/"
#weight = 4
#[[menu.nav]]
#name = "blog"
#url = "blog/"
#weight = 5
[[menu.nav]]
name = "contact"
url = "#contact"
weight = 6

# Footer Service Menu
#[[menu.service]]
#name = "graphicdesign"
#url = "service/"
#weight = 1
#[[menu.service]]
#name = "webdesign"
#url = "service/"
#weight = 2
#[[menu.service]]
#name = "webdevelopment"
#url = "service/"
#weight = 3

# Footer Quick links Menu
#[[menu.quicklink]]
#name = "about"
#url = "about/"
#weight = 1
#[[menu.quicklink]]
#name = "about"
#url = "about/"
#weight = 2
#[[menu.quicklink]]
#name = "faqs"
#url = "about/"
#weight = 3
#[[menu.quicklink]]
#name = "badges"
#url = "about/"
#weight = 4
